//Strings
const cpf = 'CPF';
const nome = 'Nome';
const email = 'Email';
const dataNascimento = 'Data de nascimento';
const salvando = 'Salvando...';
const salvar = 'Salvar';
const falha = 'Falha';
const valorIncorreto = 'Valor incorreto';
const digiteId = 'Digite o ID';
const cadastroUsuario = 'Cadastro usuário';
const conteudo = 'Content-Type';
const aplicacao = 'application/json; charset=UTF-8';
const nivel = 'Nível';
const nivelLogado = 'Nível Logado';
const senha = 'Senha';
const login = 'Login';
const alterarStatus = 'Alterar status';
const usuariosAprovados = 'Usuários aprovados';
const cadastrarNovoUsuario = 'Cadastrar novo usuário';
const usuariosReprovados = 'Usuários reprovados';
const pesquisarUsuario = 'Pesquisar usuário';
